name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./bare-minimum
        file: ./bare-minimum/Dockerfile.prod
        push: true
        tags: |
          ehtanharv/docker-bare-minimum:${{ github.sha }}
          ehtanharv/docker-bare-minimum:latest