name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      run: |
        docker build ./bare-minimum/Dockerfile.prod --tag ghcr.io/${{ github.actor }}/docker-bare-minimum:latest
        docker push ghcr.io/${{ github.actor }}/docker-bare-minimum:latest